papercorner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('',views.index,name="index"),
    path('about',views.about,name="about"),
    path('gallery',views.gallery,name="gallery"),
    path('blog',views.blog,name="blog"),
    path('contact',views.contact,name="contact")
]

web/models.py
from django.db import models

# Create your models here.

web/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,'web/index.html')

def about(request):
    return render(request,'web/about.html')

def gallery(request):
    return render(request,'web/gallery.html')

def blog(request):
    return render(request,'web/blog.html')

def contact(request):
    return render(request,'web/contact.html')

templates/web/blog.html
{% extends 'web/partials/base.html' %}

{% load static %}

{% block content %}




    <!-- ==================== Start header ==================== -->

    <header class="works-header fixed-slider hfixd valign">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-9 col-md-11 static">
                    <div class="capt mt-50">
                        <div class="parlx">
                            <h2 class="custom-font">My amazing works</h2>
                            <p>Creative way to showcase your works at their absolute best.</p>
                        </div>

                        <div class="bactxt custom-font valign">
                            <span class="full-width">Blog</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- ==================== End header ==================== -->



    <div class="main-content">

    <!-- ==================== Start Slider ==================== -->

    <header class="slider showcase-carus" data-carousel="swiper" data-items="2" data-loop="true" data-speed="1000"
        data-space="200" data-mousewheel="true" data-center="true">
        <div id="content-carousel-container-unq-1" class="swiper-container" data-swiper="container">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <div class="bg-img valign" data-background="{% static 'web/img/portfolio/full/1.jpg' %}" data-overlay-dark="1">
                        <div class="caption ontop">
                            <div class="o-hidden">
                                <h1>
                                    <a href="project-details2.html">
                                        <div class="stroke">Hoodie</div> <span>Jacket</span>
                                    </a>
                                </h1>
                            </div>
                        </div>
                        <div class="copy-cap valign">
                            <div class="cap">
                                <h1>
                                    <a href="project-details2.html">
                                        <div class="stroke">Hoodie</div> <span>Jacket</span>
                                    </a>
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="bg-img valign" data-background="{% static 'web/img/portfolio/full/4.jpg' %}" data-overlay-dark="1">
                        <div class="caption ontop">
                            <div class="o-hidden">
                                <h1>
                                    <a href="project-details2.html">
                                        <div class="stroke">Eminem</div> <span>Style</span>
                                    </a>
                                </h1>
                            </div>
                        </div>
                        <div class="copy-cap valign">
                            <div class="cap">
                                <h1>
                                    <a href="project-details2.html">
                                        <div class="stroke">Eminem</div> <span>Style</span>
                                    </a>
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="bg-img valign" data-background="{% static 'web/img/portfolio/full/5.jpg' %}" data-overlay-dark="1">
                        <div class="caption ontop">
                            <div class="o-hidden">
                                <h1>
                                    <a href="project-details2.html">
                                        <div class="stroke">Black</div> <span>Panther</span>
                                    </a>
                                </h1>
                            </div>
                        </div>
                        <div class="copy-cap valign">
                            <div class="cap">
                                <h1>
                                    <a href="project-details2.html">
                                        <div class="stroke">Black</div> <span>Panther</span>
                                    </a>
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="bg-img valign" data-background="{% static 'web/img/portfolio/full/6.jpg' %}" data-overlay-dark="1">
                        <div class="caption ontop">
                            <div class="o-hidden">
                                <h1>
                                    <a href="project-details2.html">
                                        <div class="stroke">Secret</div> <span>Office</span>
                                    </a>
                                </h1>
                            </div>
                        </div>
                        <div class="copy-cap valign">
                            <div class="cap">
                                <h1>
                                    <a href="project-details2.html">
                                        <div class="stroke">Secret</div> <span>Office</span>
                                    </a>
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- slider setting -->
            <div class="txt-botm">
                <div class="swiper-button-next swiper-nav-ctrl cursor-pointer">
                    <div>
                        <span class=" custom-font">Next Slide</span>
                    </div>
                    <div><i class="fas fa-chevron-right"></i></div>
                </div>
                <div class="swiper-button-prev swiper-nav-ctrl cursor-pointer">
                    <div><i class="fas fa-chevron-left"></i></div>
                    <div>
                        <span class=" custom-font">Prev Slide</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- ==================== End Slider ==================== -->




{% endblock %}

templates/web/contact.html
{% extends 'web/partials/base.html' %}

{% load static %}

{% block content %}


    <!-- ==================== Start header ==================== -->

    <header class="works-header fixed-slider hfixd valign">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-9 col-md-11 static">
                    <div class="capt mt-50">
                        <div class="parlx">
                            <h2 class="custom-font"><span>Let's</span>Talk About Your project.</h2>
                            <p>Feel free to ask me any question or let’s do to talk about
                                our future collaboration.</p>
                        </div>

                        <div class="bactxt custom-font valign">
                            <span class="full-width">Contact</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- ==================== End header ==================== -->


    <!-- ==================== Start main-content ==================== -->

    <div class="main-content">

        <!-- ==================== Start Contact ==================== -->

        <section class="contact section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form md-mb50">

                            <h4 class="extra-title mb-50">Get In Touch.</h4>

                            <form id="contact-form" method="post" action="https://ui-themez.smartinnovates.net/items/avo/avo-dark/contact.php">

                                <div class="messages"></div>

                                <div class="controls">

                                    <div class="form-group">
                                        <input id="form_name" type="text" name="name" placeholder="Name"
                                            required="required">
                                    </div>

                                    <div class="form-group">
                                        <input id="form_email" type="email" name="email" placeholder="Email"
                                            required="required">
                                    </div>

                                    <div class="form-group">
                                        <textarea id="form_message" name="message" placeholder="Message" rows="4"
                                            required="required"></textarea>
                                    </div>

                                    <button type="submit" class="btn-curve btn-lit"><span>Send Message</span></button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-5 offset-lg-1">
                        <div class="cont-info">
                            <h4 class="extra-title mb-50">Contact Info.</h4>
                            <h3 class="custom-font wow" data-splitting>Let's Talk.
                            </h3>
                            <div class="item mb-40">
                                <h5><a href="#0">Email@example.com</a></h5>
                                <h5>+4.930.705.5448</h5>
                            </div>
                            <h3 class="custom-font wow" data-splitting>Visit Us.
                            </h3>
                            <div class="item">
                                <h6>295 Witting Streets Suite 666,
                                    <br>Melbourne, Australia</h6>
                            </div>
                            <div class="social mt-50">
                                <a href="#0" class="icon">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                                <a href="#0" class="icon">
                                    <i class="fab fa-twitter"></i>
                                </a>
                                <a href="#0" class="icon">
                                    <i class="fab fa-pinterest"></i>
                                </a>
                                <a href="#0" class="icon">
                                    <i class="fab fa-behance"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- ==================== End Contact ==================== -->


        <!-- ==================== Start Map ==================== -->

        <!-- <div class="map" id="ieatmaps"></div> -->

        <!-- ==================== End Map ==================== -->


        <!-- ==================== Start Footer ==================== -->

{% endblock %}

templates/web/gallery.html
{% extends 'web/partials/base.html' %}

{% load static %}

{% block content %}



    <!-- ==================== Start header ==================== -->

    <header class="works-header fixed-slider hfixd valign">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-9 col-md-11 static">
                    <div class="capt mt-50">
                        <div class="parlx">
                            <h2 class="custom-font">My amazing works</h2>
                            <p>Creative way to showcase your works at their absolute best.</p>
                        </div>

                        <div class="bactxt custom-font valign">
                            <span class="full-width">Gallery</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- ==================== End header ==================== -->



    <div class="main-content">

        <!-- ==================== Start works ==================== -->

        <section class="portfolio section-padding pb-70">
            <div class="container">
                <div class="row">
    
                    <!-- filter links -->
                    <div class="filtering text-center col-12">
                        <div class="filter">
                            <span data-filter='*' class="active">All</span>
                            <span data-filter='.brand'>Branding</span>
                            <span data-filter='.web'>Mobile App</span>
                            <span data-filter='.graphic'>Creative</span>
                        </div>
                    </div>
    
                    <!-- gallery -->
                    <div class="gallery full-width">
    
                        <!-- gallery item -->
                        <div class="col-lg-4 col-md-6 items graphic lg-mr">
                            <div class="item-img wow fadeInUp" data-wow-delay=".4s">
                                <a href="project-details.html">
                                    <img src="{% static 'web/img/portfolio/mas/01.jpg' %}" alt="image">
                                    
                                </a>
                            </div>
                            <div class="cont">
                                <h6>Creativity Demand</h6>
                                <span><a href="#0">Design</a>, <a href="#0">WordPress</a></span>
                            </div>
                        </div>
    
                        <!-- gallery item -->
                        <div class="col-lg-4 col-md-6 items web">
                            <div class="item-img wow fadeInUp" data-wow-delay=".4s">
                                <a href="project-details.html">
                                    <img src="{% static 'web/img/portfolio/mas/02.jpg' %}" alt="image">
                                    
                                </a>
                            </div>
                            <div class="cont">
                                <h6>Through The Breaking</h6>
                                <span><a href="#0">Design</a>, <a href="#0">WordPress</a></span>
                            </div>
                        </div>
    
                        <!-- gallery item -->
                        <div class="col-lg-4 col-md-6 items brand lg-mr">
                            <div class="item-img wow fadeInUp" data-wow-delay=".4s">
                                <a href="project-details.html">
                                    <img src="{% static 'web/img/portfolio/mas/03.jpg' %}" alt="image">
                                    
                                </a>
                            </div>
                            <div class="cont">
                                <h6>Create With Creatives</h6>
                                <span><a href="#0">Design</a>, <a href="#0">WordPress</a></span>
                            </div>
                        </div>
    
                        <!-- gallery item -->
                        <div class="col-lg-4 col-md-6 items brand">
                            <div class="item-img wow fadeInUp" data-wow-delay=".4s">
                                <a href="project-details.html">
                                    <img src="{% static 'web/img/portfolio/mas/06.jpg' %}" alt="image">
                                    
                                </a>
                            </div>
                            <div class="cont">
                                <h6>Blast From The Past</h6>
                                <span><a href="#0">Design</a>, <a href="#0">WordPress</a></span>
                            </div>
                        </div>
    
                        <!-- gallery item -->
                        <div class="col-lg-4 col-md-6 items web">
                            <div class="item-img wow fadeInUp" data-wow-delay=".4s">
                                <a href="project-details.html">
                                    <img src="{% static 'web/img/portfolio/mas/05.jpg' %}" alt="image">
                                    
                                </a>
                            </div>
                            <div class="cont">
                                <h6>See It Yourself</h6>
                                <span><a href="#0">Design</a>, <a href="#0">WordPress</a></span>
                            </div>
                        </div>
    
                        <!-- gallery item -->
                        <div class="col-lg-4 col-md-6 items graphic">
                            <div class="item-img wow fadeInUp" data-wow-delay=".4s">
                                <a href="project-details.html">
                                    <img src="{% static 'web/img/portfolio/mas/04.jpg' %}" alt="image">
                                    
                                </a>
                            </div>
                            <div class="cont">
                                <h6>Energies of Love</h6>
                                <span><a href="#0">Design</a>, <a href="#0">WordPress</a></span>
                            </div>
                        </div>
    
                    </div>
    
                </div>
            </div>
        </section>

        <!-- ==================== End works ==================== -->

        <!-- ==================== Start Footer ==================== -->

{% endblock %}

templates/web/partials/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">


<!-- Mirrored from ui-themez.smartinnovates.net/items/avo/avo-dark/index2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 04 Dec 2022 09:29:06 GMT -->
<head>

    <!-- Metas -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="keywords" content="HTML5 Template Avo onepage themeforest" />
    <meta name="description" content="Avo - Onepage Multi-Purpose HTML5 Template" />
    <meta name="author" content="" />

    <!-- Title  -->
    <title>Avo</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'web/img/favicon.ico' %}" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&amp;display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,500,600,700,800,900&amp;display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400;500;600;700&amp;display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@200;300;400;500;600;700&amp;display=swap"
        rel="stylesheet">

    <!-- Plugins -->
    <link rel="stylesheet" href="{% static 'web/css/plugins.css' %}" />

    <!-- Core Style Css -->
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}" />

</head>



{% include 'web/partials/header.html' %}


{% block content %}


{% endblock %}


{% include 'web/partials/footer.html' %}



    <!-- jQuery -->
    <script src="{% static 'web/js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'web/js/jquery-migrate-3.0.0.min.js' %}"></script>

    <!-- plugins -->
    <script src="{% static 'web/js/plugins.js' %}"></script>

    <!-- custom scripts -->
    <script src="{% static 'web/js/scripts.js' %}"></script>

</body>


<!-- Mirrored from ui-themez.smartinnovates.net/items/avo/avo-dark/index2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 04 Dec 2022 09:29:25 GMT -->
</html>

templates/web/partials/footer.html
{% load static %}
    
    <!-- ==================== Start Footer ==================== -->

    <footer class="footer-half sub-bg section-padding pb-0">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <div class="cont">
                        <div class="logo">
                            <a href="#0">
                                <img src="{% static 'web/img/pc12.svg' %}" alt="">
                            </a>
                        </div>
                        <div class="con-info custom-font">
                            <ul>
                                <li><span>Email : </span> Avo_support@website.com</li>
                                <li><span>Address : </span> A32 , Ave 15th Street, Door 211, San Franciso, USA 32490.
                                </li>
                                <li><span>Phone : </span> (+1) 2345 678 44 88</li>
                            </ul>
                        </div>
                        <div class="social-icon">
                            <h6 class="custom-font stit simple-btn">Follow Us</h6>
                            <div class="social">
                                <a href="#0" class="icon">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                                <a href="#0" class="icon">
                                    <i class="fab fa-twitter"></i>
                                </a>
                                <a href="#0" class="icon">
                                    <i class="fab fa-pinterest"></i>
                                </a>
                                <a href="#0" class="icon">
                                    <i class="fab fa-behance"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 offset-lg-2">
                    <div class="subscribe mb-50">
                        <h6 class="custom-font stit simple-btn">Newslatter</h6>
                        <p>Sign up for subscribe out newsletter!</p>
                        <form>
                            <div class="form-group custom-font">
                                <input type="email" name="subscribe" placeholder="Your Email">
                                <button class="cursor-pointer">Subscribe</button>
                            </div>
                        </form>
                    </div>
                    <div class="insta">
                        <h6 class="custom-font stit simple-btn">Instagram Post</h6>
                        <div class="insta-gallary">
                            <a href="#0">
                                <img src="{% static 'web/img/insta/1.jpg' %}" alt="">
                            </a>
                            <a href="#0">
                                <img src="{% static 'web/img/insta/2.jpg' %}" alt="">
                            </a>
                            <a href="#0">
                                <img src="{% static 'web/img/insta/3.jpg' %}" alt="">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyrights text-center">
                <p>© 2020, Avo Template. Made with passion by <a href="#0">UI-ThemeZ</a>.</p>
            </div>
        </div>
    </footer>

    <!-- ==================== End Footer ==================== -->

templates/web/partials/header.html
{% load static %}

<body>



    <!-- ==================== Start Loading ==================== -->

    <div id="preloader">
    </div>

    <!-- ==================== End Loading ==================== -->


    <!-- ==================== Start progress-scroll-button ==================== -->

    <div class="progress-wrap cursor-pointer">
        <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
            <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
        </svg>
    </div>

    <!-- ==================== End progress-scroll-button ==================== -->


    <!-- ==================== Start cursor ==================== -->

    <div class="mouse-cursor cursor-outer"></div>
    <div class="mouse-cursor cursor-inner"></div>

    <!-- ==================== End cursor ==================== -->



    <!-- ==================== Start Navbar ==================== -->

    <nav class="navbar navbar-expand-lg">
        <div class="container">

            <!-- Logo -->
            <a class="logo" href="#">
                <img src="{% static 'web/img/pc12.svg' %}" style="height:150px; width:88px;" alt="logo">
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="icon-bar"><i class="fas fa-bars"></i></span>
            </button>

            <!-- navbar links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'web:index' %}" role="button"
                            aria-haspopup="true" aria-expanded="false">Home</a>
                        <!-- <div class="dropdown-menu">
                            <a class="dropdown-item" href="index.html">Main Home</a>
                        </div> -->
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'web:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'web:gallery' %}" role="button"
                            aria-haspopup="true" aria-expanded="false">Gallery</a>
                            <!-- dropdown-toggle -->
                        <!-- <div class="dropdown-menu">
                            <a class="dropdown-item" href="works.html">Mouse Info</a>
                            <a class="dropdown-item" href="works2.html">Masonry 3 Columns</a>
                            <a class="dropdown-item" href="works3.html">Masonry 2 Columns</a>
                            <a class="dropdown-item" href="works4.html">Pinterest List</a>
                        </div> -->
                    </li>
                    <li class="nav-item">
                        <!-- dropdown -->
                        <a class="nav-link" href="{% url 'web:blog' %}" role="button"
                            aria-haspopup="true" aria-expanded="false">Blog</a>
                        <!-- <div class="dropdown-menu">
                            <a class="dropdown-item" href="showcase.html">Full Screen</a>
                            <a class="dropdown-item" href="showcase2.html">Creative Carousel</a>
                            <a class="dropdown-item" href="showcase3.html">Radius Carousel</a>
                            <a class="dropdown-item" href="showcase4.html">Columns Carousel</a>
                        </div> -->
                    </li>
                    
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'web:contact' %}">Contact</a>
                    </li>
                </ul>
                <!-- <div class="search">
                    <span class="icon pe-7s-search cursor-pointer"></span>
                    <div class="search-form text-center custom-font">
                        <form>
                            <input type="text" name="search" placeholder="Search">
                        </form>
                        <span class="close pe-7s-close cursor-pointer"></span>
                    </div>
                </div> -->
            </div>
        </div>
    </nav>

    <!-- ==================== End Navbar ==================== -->



   